version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/edutube
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - edutube-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edutube
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edutube-network

  redis:
    image: redis:6
    command: redis-server --requirepass your-redis-password-here
    volumes:
      - redis_data:/data
    networks:
      - edutube-network

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/edutube
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - web
      - db
      - redis
    networks:
      - edutube-network

volumes:
  postgres_data:
  redis_data:

networks:
  edutube-network:
    driver: bridge 